// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Async: typeof import('./components/Async/index.vue')['default']
    Card: typeof import('./components/Card/index.vue')['default']
    CustomDirect: typeof import('./components/CustomDirect.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    DefaultSlot: typeof import('./components/Slot/DefaultSlot.vue')['default']
    EventBusA: typeof import('./components/EventBus/EventBusA.vue')['default']
    EventBusB: typeof import('./components/EventBus/EventBusB.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    Login: typeof import('./components/Login/index.vue')['default']
    MittA: typeof import('./components/MittProp/MittA.vue')['default']
    MittB: typeof import('./components/MittProp/MittB.vue')['default']
    ModelButton: typeof import('./components/ModelButton/index.vue')['default']
    MyModifier: typeof import('./components/MyModifier.vue')['default']
    NextTick: typeof import('./components/NextTick.vue')['default']
    PiniaTest: typeof import('./components/PiniaTest.vue')['default']
    ProvideInject: typeof import('./components/ProvideInject/index.vue')['default']
    ProvideInjectA: typeof import('./components/ProvideInject/ProvideInjectA.vue')['default']
    ProvideInjectB: typeof import('./components/ProvideInject/ProvideInjectB.vue')['default']
    Register: typeof import('./components/Register/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLogin: typeof import('./components/Router/RouterLogin.vue')['default']
    RouterRegister: typeof import('./components/Router/RouterRegister.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ScopedStyle: typeof import('./components/ScopedStyle.vue')['default']
    SiblingA: typeof import('./components/SiblingProp/SiblingA.vue')['default']
    SiblingB: typeof import('./components/SiblingProp/SiblingB.vue')['default']
    Tree: typeof import('./components/Tree/index.vue')['default']
  }
}

export {}
